version: '3.1'

services:
  verdaccio:
    image: verdaccio/verdaccio
    container_name: 'verdaccio'
    networks:
      - node-network
    environment:
      - VERDACCIO_PORT=4873
    ports:
      - '4873:4873'
    volumes:
      - './storage:/verdaccio/storage'
      - './config:/verdaccio/conf'
      - './plugins:/verdaccio/plugins'
  node:
    image: "node:8"
    user: "node"
    working_dir: /home/tori/Documents/project
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/tori/Documents/project
    expose:
      - "8081"
    ports: 
      - "8001:8001"
    command: "npm start" #?
networks:
  node-network:
    driver: bridge